import type { CuratedDish } from './curatedCatalog';

// Reviewed dishes. One row names a real meal, its required foods and the
// two dish-specific cooking actions; shared preparation, safe finish and
// serving steps are provided below. Never cross-product foods with formats.
// Columns: English title | Spanish title | foods | method | minutes |
// English cook | Spanish cook | English finish | Spanish finish.
const rows = `
Chicken Tinga Tostadas|Tostadas de tinga de pollo|chicken,tostadas,tomatoes,onion|Stove|35|Simmer chicken with tomatoes and onion until cooked through, then shred it into the sauce.|Cuece el pollo con jitomate y cebolla hasta que esté bien cocido; deshébralo en la salsa.|Spread saucy chicken on each tostada just before serving.|Pon el pollo con salsa sobre las tostadas justo antes de servir.
Lemon Chicken Orzo|Pollo al limón con orzo|chicken,orzo,lemon,spinach|Stove|30|Brown chicken pieces, then simmer orzo with water and lemon zest until tender.|Dora trozos de pollo; cuece el orzo con agua y ralladura de limón hasta ablandarlo.|Fold in spinach until wilted and squeeze lemon over the pan.|Incorpora espinacas hasta que se marchiten y exprime limón encima.
Chicken and Mushroom Stroganoff|Pollo con champiñones en salsa cremosa|chicken,mushrooms,yogurt,pasta|Stove|35|Sauté chicken and mushrooms separately; boil the pasta until tender.|Saltea pollo y champiñones por separado; hierve la pasta hasta que esté suave.|Take the pan off the heat, stir in yogurt and toss with pasta to avoid curdling.|Retira del fuego, agrega yogur y mezcla con la pasta para que no se corte.
Chicken Pesto Pasta|Pasta de pollo al pesto|chicken,pasta,pesto,tomatoes|Stove|25|Cook pasta and sear bite-size chicken in a separate skillet until done.|Cuece la pasta y dora el pollo en trozos en otro sartén hasta que esté cocido.|Mix pesto with a splash of pasta water, then toss with chicken and tomatoes.|Afloja el pesto con un poco de agua de la pasta y mezcla con pollo y jitomate.
Chicken Noodle Soup|Sopa de fideos con pollo|chicken,noodles,carrot,celery|Stove|35|Simmer chicken and sliced carrots in broth or water until chicken is done.|Cuece pollo y zanahoria rebanada en caldo o agua hasta que el pollo esté cocido.|Add noodles and celery; simmer until the noodles are tender.|Agrega fideos y apio; cocina hasta que los fideos estén suaves.
Chicken and Broccoli Stir Fry|Salteado de pollo con brócoli|chicken,broccoli,rice,soy sauce|Stove|25|Cook rice; sear thin chicken strips in a hot skillet until done.|Cuece el arroz; dora tiras finas de pollo en un sartén caliente hasta cocerlas.|Steam broccoli briefly, then toss it with chicken and soy sauce.|Cuece brevemente el brócoli al vapor y mézclalo con pollo y salsa de soya.
Chicken Caesar Wraps|Wraps de pollo estilo César|chicken,tortillas,lettuce,parmesan,caesar dressing|Stove|25|Cook seasoned chicken in a skillet and slice it thinly after a short rest.|Cocina el pollo sazonado en un sartén y córtalo fino después de reposar.|Fill warm tortillas with chicken, washed lettuce and grated parmesan.|Rellena tortillas tibias con pollo, lechuga lavada y parmesano rallado.
Chicken Parmesan Cutlets|Milanesas de pollo con tomate y queso|chicken,breadcrumbs,tomatoes,mozzarella|Oven|35|Coat thin chicken cutlets in breadcrumbs; bake until golden and cooked through.|Cubre filetes delgados de pollo con pan molido y hornéalos hasta dorar y cocer.|Top with warm tomato sauce and mozzarella; return to oven until melted.|Cubre con salsa de jitomate caliente y mozzarella; hornea hasta derretir.
Chicken Souvlaki Pitas|Pitas de pollo al limón|chicken,pita,cucumber,yogurt,lemon|Stove|30|Sear chicken cubes with lemon and oregano until browned and cooked.|Dora cubos de pollo con limón y orégano hasta cocerlos por completo.|Stuff warm pitas with chicken, cucumber and yogurt.|Rellena las pitas calientes con pollo, pepino y yogur.
Chicken and Sweet Potato Curry|Curry de pollo y camote|chicken,sweet potatoes,coconut milk,rice|Stove|40|Simmer diced sweet potatoes in coconut milk and curry spices until nearly soft.|Cuece cubos de camote en leche de coco con especias de curry hasta casi ablandar.|Add chicken cubes, simmer until done, and serve over cooked rice.|Agrega cubos de pollo, cocina hasta que estén bien hechos y sirve sobre arroz.
Chicken Enchiladas Verdes|Enchiladas verdes de pollo|chicken,tortillas,salsa verde,cheese|Oven|40|Cook and shred chicken; soften tortillas in a dry skillet.|Cuece y deshebra el pollo; calienta las tortillas en un sartén seco.|Roll chicken in tortillas, cover with salsa verde and cheese, then bake until hot.|Enrolla el pollo en tortillas, cubre con salsa verde y queso y hornea hasta calentar.
Chicken and Corn Chowder|Crema de pollo y elote|chicken,corn,potatoes,milk|Stove|40|Simmer diced potatoes and corn in water or broth until potatoes soften.|Cuece papas picadas y elote en agua o caldo hasta ablandar las papas.|Add chicken and milk; simmer gently until chicken cooks through without boiling the milk hard.|Agrega pollo y leche; cuece suave hasta cocinar el pollo sin hervir fuerte la leche.
Chicken Greek Rice Bowls|Tazones griegos de pollo y arroz|chicken,rice,cucumber,tomatoes,lemon|Stove|30|Cook rice and pan-sear chicken with oregano and lemon until done.|Cuece el arroz y dora el pollo con orégano y limón hasta cocinarlo.|Add chopped cucumber and tomatoes to the rice; arrange the chicken on top.|Agrega pepino y jitomate picados al arroz y coloca el pollo encima.
Chicken and Vegetable Pot Pie|Pay de pollo con verduras|chicken,peas,carrot,pastry|Oven|50|Cook chicken and carrots in a skillet; thicken the pan juices with flour and water.|Cuece pollo y zanahoria en sartén; espesa los jugos con harina y agua.|Stir in peas, cover with pastry and bake until puffed and golden.|Incorpora chícharos, cubre con masa y hornea hasta que dore.
Chicken Lettuce Cups|Tacos de lechuga con pollo|chicken,lettuce,carrot,soy sauce|Stove|25|Mince chicken finely and cook it with grated carrot in a skillet.|Pica fino el pollo y cocínalo con zanahoria rallada en un sartén.|Season with soy sauce and spoon into washed lettuce leaves.|Sazona con salsa de soya y sirve sobre hojas de lechuga lavadas.
Chicken and White Bean Stew|Guiso de pollo y alubias|chicken,white beans,tomatoes,spinach|Stove|35|Simmer diced chicken with crushed tomatoes until fully cooked.|Cuece cubos de pollo con jitomate triturado hasta cocinarlo por completo.|Add drained white beans and spinach; simmer until hot and wilted.|Agrega alubias escurridas y espinacas; cocina hasta calentar y marchitar.
Chicken and Cabbage Skillet|Pollo salteado con repollo|chicken,cabbage,onion,carrot|Stove|25|Sear chicken strips until done; transfer to a clean plate.|Dora tiras de pollo hasta cocerlas; pásalas a un plato limpio.|Sauté cabbage, onion and carrot until tender; return chicken to warm together.|Saltea repollo, cebolla y zanahoria hasta ablandar; agrega de nuevo el pollo.
Honey Garlic Chicken Thighs|Muslos de pollo con ajo y miel|chicken,honey,garlic,rice|Oven|40|Bake chicken thighs in an oiled dish until nearly cooked through.|Hornea muslos de pollo en un recipiente aceitado hasta que casi estén cocidos.|Brush with honey and garlic; bake until glossy and chicken reaches safe temperature.|Barniza con miel y ajo; hornea hasta glasear y alcanzar temperatura segura.
Chicken and Spinach Lasagna|Lasaña de pollo y espinacas|chicken,lasagna sheets,spinach,ricotta,tomatoes|Oven|55|Cook and shred chicken; layer lasagna sheets with spinach and ricotta.|Cuece y deshebra el pollo; alterna láminas de lasaña con espinacas y ricotta.|Pour tomato sauce and water between layers; cover and bake until pasta is tender.|Reparte salsa de jitomate y agua entre capas; tapa y hornea hasta ablandar la pasta.
Chicken and Avocado Sandwich|Sándwich de pollo y aguacate|chicken,bread,avocado,lettuce|Stove|20|Pan-cook thin chicken pieces until completely done, then let them rest.|Cocina filetes delgados de pollo en sartén hasta cocerlos bien y deja reposar.|Layer chicken, sliced avocado and washed lettuce between toasted bread.|Coloca pollo, aguacate rebanado y lechuga lavada entre panes tostados.
Chicken Pozole Verde|Pozole verde de pollo|chicken,hominy,tomatillos,radishes|Stove|55|Simmer chicken in water until done; shred and reserve its broth.|Cuece el pollo en agua hasta cocinarlo; deshebra y reserva el caldo.|Blend cooked tomatillos, return with hominy and chicken to broth; simmer and garnish with radish.|Licua tomatillos cocidos, regrésalos al caldo con maíz pozolero y pollo; sirve con rábano.
Chicken and Black Bean Burritos|Burritos de pollo y frijoles negros|chicken,black beans,tortillas,rice|Stove|30|Cook rice and sauté small chicken pieces until thoroughly cooked.|Cuece el arroz y saltea trozos de pollo hasta cocerlos completamente.|Warm drained beans; tuck all three into tortillas and toast the seams briefly.|Calienta frijoles escurridos; envuelve todo en tortillas y dora la unión.
Lemon Herb Chicken with Green Beans|Pollo al limón con ejotes|chicken,green beans,lemon,potatoes|Oven|40|Roast small potato pieces on a tray; add seasoned chicken after ten minutes.|Hornea trozos pequeños de papa; agrega pollo sazonado a los diez minutos.|Add green beans for the last ten minutes, then squeeze lemon on the cooked chicken.|Agrega ejotes los últimos diez minutos y exprime limón sobre el pollo cocido.
Chicken and Pineapple Rice|Arroz con pollo y piña|chicken,pineapple,rice,bell pepper|Stove|30|Cook rice, then sear chicken cubes separately until cooked through.|Cuece el arroz; dora cubos de pollo por separado hasta que estén bien cocidos.|Sauté pepper and pineapple until lightly browned; fold into the rice with chicken.|Saltea pimiento y piña hasta dorar ligeramente; mezcla con arroz y pollo.
Chicken and Zucchini Meatballs|Albóndigas de pollo con calabacita|ground chicken,zucchini,breadcrumbs,tomatoes|Oven|40|Mix ground chicken with grated zucchini and breadcrumbs; form equal meatballs.|Mezcla pollo molido con calabacita rallada y pan molido; forma albóndigas parejas.|Bake until cooked through, then coat with simmered tomato sauce.|Hornea hasta cocer por completo y cubre con salsa de jitomate caliente.
Beef and Broccoli Stir Fry|Salteado de res con brócoli|steak,broccoli,rice,soy sauce|Stove|25|Cook rice; sear thin strips of beef quickly in a hot skillet.|Cuece arroz; dora rápidamente tiras delgadas de res en un sartén caliente.|Steam broccoli until crisp-tender, then toss with beef and soy sauce.|Cuece brócoli al vapor hasta suavizar y mézclalo con la res y salsa de soya.
Beef Bolognese|Espagueti a la boloñesa|ground beef,pasta,tomatoes,carrot|Stove|40|Brown ground beef, then simmer with grated carrot and crushed tomatoes.|Dora carne molida y cuece con zanahoria rallada y jitomate triturado.|Boil pasta separately and toss it into the reduced meat sauce.|Hierve la pasta aparte y mézclala con la salsa de carne reducida.
Beef and Barley Soup|Sopa de res con cebada|stew beef,barley,carrot,celery|Stove|75|Simmer beef with water until tender, skimming the surface when needed.|Cuece res con agua hasta que ablande, retirando espuma si es necesario.|Add barley, carrot and celery; simmer until the grains are tender.|Agrega cebada, zanahoria y apio; cuece hasta ablandar el grano.
Beef Stuffed Bell Peppers|Pimientos rellenos de carne y arroz|ground beef,bell pepper,rice,tomatoes|Oven|45|Brown ground beef; mix it with cooked rice and chopped tomatoes.|Dora carne molida; mézclala con arroz cocido y jitomate picado.|Fill halved peppers and bake covered until peppers are tender.|Rellena mitades de pimiento y hornea tapado hasta que se ablanden.
Beef and Potato Empanadas|Empanadas de carne y papa|ground beef,potatoes,pastry,onion|Oven|50|Cook diced potato until soft; brown ground beef with minced onion.|Cuece papa picada hasta suavizar; dora carne molida con cebolla picada.|Fold filling inside pastry circles, seal edges and bake until golden.|Rellena discos de masa, sella los bordes y hornea hasta dorar.
Swedish-Style Beef Meatballs|Albóndigas de res en salsa cremosa|ground beef,breadcrumbs,milk,potatoes|Stove|40|Mix beef, breadcrumbs and a little milk; shape and brown the meatballs.|Mezcla carne, pan molido y poca leche; forma albóndigas y dóralas.|Simmer meatballs in pan gravy until done and serve with mashed potatoes.|Cuece las albóndigas en salsa del sartén hasta que estén hechas; sirve con puré.
Beef and Cabbage Rolls|Rollitos de repollo rellenos de res|ground beef,cabbage,rice,tomatoes|Oven|60|Soften cabbage leaves in hot water; mix ground beef with cooked rice.|Ablanda hojas de repollo en agua caliente; mezcla carne molida con arroz cocido.|Roll filling in leaves, cover with tomato sauce and bake until centers are fully cooked.|Enrolla el relleno en las hojas, cubre de salsa y hornea hasta cocer los centros.
Steak and Mushroom Sandwich|Sándwich de bistec y champiñones|steak,mushrooms,bread,onion|Stove|25|Sear sliced steak in batches and let it rest on a clean plate.|Dora bistec en tiras por tandas y deja reposar en plato limpio.|Brown mushrooms and onion in the same skillet, then pile everything on toast.|Dora champiñones y cebolla en el mismo sartén y sirve todo sobre pan tostado.
Beef and Bean Chili|Chili de res y frijoles|ground beef,kidney beans,tomatoes,onion|Stove|35|Brown ground beef with onion; drain excess fat.|Dora carne molida con cebolla y retira el exceso de grasa.|Add beans, tomatoes and chili powder; simmer until thick and hot.|Agrega frijoles, jitomate y chile en polvo; cuece hasta espesar.
Beef and Zucchini Skillet|Picadillo de res con calabacita|ground beef,zucchini,tomatoes,corn|Stove|30|Brown ground beef, breaking it into small pieces.|Dora la carne molida separándola en trozos pequeños.|Simmer with diced zucchini, tomatoes and corn until zucchini is tender.|Cuece con calabacita, jitomate y elote hasta ablandar la calabacita.
Beef Kofta with Cucumber Yogurt|Kofta de res con salsa de pepino|ground beef,cucumber,yogurt,pita|Stove|30|Shape seasoned beef into small oblong patties; sear on all sides until done.|Forma pequeñas tortitas alargadas de res sazonada y dóralas hasta cocer.|Grate cucumber into yogurt and serve the patties with warm pita.|Ralla pepino en yogur y sirve las tortitas con pita caliente.
Beef and Tomato Stuffed Zucchini|Calabacitas rellenas de res|ground beef,zucchini,tomatoes,cheese|Oven|40|Scoop out zucchini halves; brown ground beef with chopped tomatoes.|Ahueca mitades de calabacita; dora carne molida con jitomate picado.|Fill zucchini with cooked beef, sprinkle cheese and bake until tender.|Rellena las calabacitas con carne, agrega queso y hornea hasta ablandar.
Beef and Eggplant Moussaka|Musaca de res y berenjena|ground beef,eggplant,tomatoes,yogurt|Oven|60|Roast eggplant slices; cook beef with tomato until fully browned.|Asa rebanadas de berenjena; cocina la res con jitomate hasta dorarla bien.|Layer eggplant and beef, spread yogurt on top and bake until bubbling.|Alterna berenjena y res, cubre con yogur y hornea hasta burbujear.
Steak and Potato Hash|Picadillo de bistec y papas|steak,potatoes,onion,bell pepper|Stove|35|Pan-fry small potato cubes until soft and browned.|Dora cubitos de papa en sartén hasta que queden suaves.|Sear steak pieces separately, then toss with potatoes, pepper and onion.|Dora trocitos de bistec aparte y mezcla con papas, pimiento y cebolla.
Beef and Rice Stuffed Tomatoes|Jitomates rellenos de res y arroz|ground beef,tomatoes,rice,onion|Oven|40|Hollow out firm tomatoes; brown beef and onion, then combine with cooked rice.|Ahueca jitomates firmes; dora res y cebolla y mezcla con arroz cocido.|Fill tomatoes and bake until soft and the beef filling is piping hot.|Rellena jitomates y hornea hasta que ablanden y el relleno esté bien caliente.
Beef Teriyaki Rice Bowls|Tazones de res teriyaki|steak,rice,broccoli,teriyaki sauce|Stove|25|Cook rice and sear thin steak slices over high heat.|Cuece arroz y dora rebanadas finas de bistec a fuego alto.|Add steamed broccoli and teriyaki sauce to coat the beef; serve over rice.|Agrega brócoli al vapor y salsa teriyaki para cubrir la res; sirve sobre arroz.
Beef and Spinach Lasagna|Lasaña de carne y espinacas|ground beef,lasagna sheets,spinach,ricotta,tomatoes|Oven|60|Brown ground beef and wilt spinach separately; prepare tomato sauce.|Dora la carne molida y marchita las espinacas por separado; prepara salsa roja.|Layer pasta, meat, spinach, ricotta and sauce; cover and bake until pasta is tender.|Alterna pasta, carne, espinacas, ricotta y salsa; tapa y hornea hasta ablandar.
Beef and Potato Shepherd's Pie|Pastel de carne y papa|ground beef,potatoes,peas,carrot|Oven|50|Boil and mash potatoes; brown beef with diced carrots in a pan.|Hierve y machaca papas; dora res con zanahoria picada en un sartén.|Stir peas into beef, spread mashed potatoes on top and bake until browned.|Agrega chícharos a la res, cubre con puré y hornea hasta dorar.
Pork Carnitas Tacos|Tacos de carnitas de cerdo|pork,tortillas,onion,orange|Stove|100|Simmer pork pieces with orange juice and water until fork-tender.|Cuece trozos de cerdo con jugo de naranja y agua hasta que se deshebren.|Shred and crisp the meat in its own juices; serve with onion in tortillas.|Deshebra y dora la carne en sus jugos; sirve con cebolla en tortillas.
Pork and Pineapple Skewers|Brochetas de cerdo y piña|pork,pineapple,bell pepper,onion|Oven|40|Thread equal-size pork, pineapple and pepper onto skewers; place on a tray.|Ensarta trozos parejos de cerdo, piña y pimiento; coloca en charola.|Bake and turn until pork is cooked through and the pineapple browns.|Hornea y voltea hasta cocinar el cerdo y dorar la piña.
Pork Chops with Apple|Chuletas de cerdo con manzana|pork chops,apple,onion,potatoes|Stove|35|Pan-sear pork chops on both sides; finish over moderate heat.|Dora las chuletas por ambos lados y termina a fuego medio.|Cook sliced apple and onion in the same pan; serve with boiled potatoes.|Cocina manzana y cebolla rebanadas en el mismo sartén; sirve con papas cocidas.
Pork Green Chile Stew|Guiso de cerdo en salsa verde|pork,tomatillos,potatoes,onion|Stove|60|Brown pork cubes, then simmer in water until nearly tender.|Dora cubos de cerdo y cuécelos en agua hasta casi ablandar.|Add blended cooked tomatillos and diced potato; cook until tender.|Agrega tomatillos cocidos licuados y papa picada; cocina hasta suavizar.
Pork Fried Rice|Arroz frito con cerdo|pork,rice,peas,eggs|Stove|30|Cook pork pieces in a skillet until done; scramble eggs in a separate spot.|Cocina trocitos de cerdo hasta que estén hechos; revuelve huevos a un lado.|Add cold cooked rice and peas; stir-fry until very hot and evenly mixed.|Añade arroz cocido frío y chícharos; saltea hasta calentar bien.
Pork and Mushroom Noodles|Fideos salteados con cerdo y hongos|pork,noodles,mushrooms,soy sauce|Stove|30|Cook noodles according to package; sauté pork strips until done.|Cuece los fideos según el paquete; saltea tiras de cerdo hasta cocerlas.|Brown mushrooms; toss with noodles, pork and soy sauce.|Dora champiñones; mezcla con fideos, cerdo y salsa de soya.
Pulled Pork Sandwich|Sándwich de cerdo deshebrado|pork,bread,cabbage,barbecue sauce|Stove|100|Simmer pork covered with water until tender enough to shred.|Cuece cerdo tapado con agua hasta poder deshebrarlo.|Reduce the cooking liquid with barbecue sauce and pork; serve with slaw on bread.|Reduce el líquido con salsa barbacoa y cerdo; sirve con repollo en pan.
Turkey and Spinach Meatballs|Albóndigas de pavo y espinacas|turkey,spinach,breadcrumbs,tomatoes|Oven|40|Mix ground turkey with chopped spinach and breadcrumbs; shape even balls.|Mezcla pavo molido con espinacas picadas y pan molido; forma bolas parejas.|Bake until fully cooked and coat with warm tomato sauce.|Hornea hasta cocer por completo y cubre con salsa de jitomate caliente.
Turkey and Rice Stuffed Peppers|Pimientos rellenos de pavo|turkey,bell pepper,rice,tomatoes|Oven|45|Brown ground turkey and combine with cooked rice and chopped tomatoes.|Dora pavo molido y mézclalo con arroz cocido y jitomate picado.|Fill pepper halves, cover and bake until tender and piping hot.|Rellena pimientos, tapa y hornea hasta ablandar y calentar bien.
Turkey and Sweet Potato Chili|Chili de pavo y camote|turkey,sweet potatoes,black beans,tomatoes|Stove|45|Brown ground turkey; add diced sweet potatoes and crushed tomatoes.|Dora pavo molido; agrega camote en cubos y jitomate triturado.|Simmer with drained black beans until sweet potatoes are tender.|Cuece con frijoles negros escurridos hasta ablandar el camote.
Turkey Lettuce Burgers|Hamburguesas de pavo con lechuga|turkey,lettuce,tomatoes,onion|Stove|25|Shape ground turkey into patties and cook both sides until fully done.|Forma tortitas de pavo molido y cocínalas bien por ambos lados.|Wrap in large washed lettuce leaves with tomato and onion.|Envuelve en hojas grandes de lechuga lavada con jitomate y cebolla.
Turkey and Vegetable Soup|Sopa de pavo con verduras|turkey,carrot,celery,potatoes|Stove|45|Simmer turkey in water with diced carrots and celery until cooked.|Cuece pavo en agua con zanahoria y apio picados hasta cocinarlo.|Add potato cubes and simmer until soft; break up any large pieces of turkey.|Agrega papas en cubos y cuece hasta suavizar; desmenuza los trozos grandes.
Turkey and Zucchini Skillet|Salteado de pavo y calabacita|turkey,zucchini,onion,tomatoes|Stove|30|Brown ground turkey with chopped onion until fully cooked.|Dora pavo molido con cebolla picada hasta cocerlo bien.|Add zucchini and tomato and cook until the zucchini softens.|Agrega calabacita y jitomate y cocina hasta que se suavice.
Turkey and Cranberry Panini|Panini de pavo con arándanos|cooked turkey,bread,cheese,cranberry sauce|Stove|15|Warm pre-cooked turkey thoroughly and toast the bread lightly.|Calienta bien pavo previamente cocido y tuesta el pan ligeramente.|Layer turkey, cheese and cranberry sauce; press in a skillet until melted.|Coloca pavo, queso y salsa de arándanos; presiona en sartén hasta derretir.
Turkey and Bean Taco Salad|Ensalada de tacos con pavo y frijoles|turkey,beans,lettuce,tomatoes|Stove|25|Brown ground turkey until fully cooked and warm drained beans.|Dora pavo molido hasta que esté bien cocido y calienta frijoles escurridos.|Layer over washed lettuce with chopped tomatoes; keep any dressing separate.|Sirve sobre lechuga lavada con jitomates picados; deja el aderezo aparte.
Pork and Cabbage Dumplings|Empanaditas de cerdo y repollo|ground pork,cabbage,dumpling wrappers,ginger|Stove|45|Mix ground pork with shredded cabbage and ginger; seal in wrappers.|Mezcla cerdo molido con repollo rallado y jengibre; sella en obleas.|Brown bases in a covered skillet with a splash of water until pork filling is done.|Dora las bases en sartén tapado con poca agua hasta cocer el relleno.
Pork and Bean Cassoulet|Guiso de cerdo y alubias|pork,white beans,carrot,tomatoes|Stove|55|Brown pork cubes, then simmer with carrot and tomatoes until tender.|Dora cubos de cerdo; cuece con zanahoria y jitomate hasta ablandar.|Add drained white beans and reduce to a thick spoonable stew.|Agrega alubias escurridas y reduce hasta obtener un guiso espeso.
Pork and Broccoli Rice Bowls|Tazones de cerdo, brócoli y arroz|pork,broccoli,rice,soy sauce|Stove|30|Cook rice; sear thin pork strips in a skillet until fully cooked.|Cuece arroz; dora tiras finas de cerdo hasta cocer por completo.|Steam broccoli and toss with pork and soy sauce before serving over rice.|Cuece brócoli al vapor y mezcla con cerdo y soya antes de servir con arroz.
Pork and Apple Meatballs|Albóndigas de cerdo y manzana|ground pork,apple,breadcrumbs,onion|Oven|40|Mix ground pork with grated apple, minced onion and breadcrumbs.|Mezcla cerdo molido con manzana rallada, cebolla picada y pan molido.|Shape into small balls and bake until centers are completely cooked.|Forma bolitas y hornea hasta cocinar bien los centros.
Turkey and Mushroom Pasta|Pasta con pavo y champiñones|turkey,mushrooms,pasta,tomatoes|Stove|35|Brown ground turkey with sliced mushrooms; boil pasta separately.|Dora pavo molido con champiñones; hierve la pasta aparte.|Add chopped tomatoes, simmer briefly and toss with the pasta.|Agrega jitomates picados, cuece unos minutos y mezcla con la pasta.
`;
const moreRows = `
Salmon Cakes with Lemon|Tortitas de salmón con limón|canned salmon,eggs,breadcrumbs,lemon|Stove|25|Mix drained canned salmon with egg and breadcrumbs; form compact cakes.|Mezcla salmón enlatado escurrido con huevo y pan molido; forma tortitas.|Pan-fry on both sides until golden and set; squeeze lemon over them.|Dora en sartén por ambos lados hasta cuajar y exprime limón encima.
Salmon with Dill Potatoes|Salmón con papas al eneldo|salmon,potatoes,lemon,dill|Oven|35|Roast small potatoes until almost tender; place salmon beside them.|Hornea papas pequeñas hasta casi ablandar; coloca salmón a su lado.|Bake until fish is cooked, then scatter dill and lemon juice.|Hornea hasta cocinar el pescado y agrega eneldo y jugo de limón.
Salmon Teriyaki Bowls|Tazones de salmón teriyaki|salmon,rice,broccoli,teriyaki sauce|Stove|30|Cook rice and steam broccoli separately; sear salmon until cooked.|Cuece arroz y brócoli al vapor por separado; dora salmón hasta cocer.|Glaze the cooked fish with teriyaki sauce and serve over rice with broccoli.|Barniza el pescado cocido con teriyaki y sirve con arroz y brócoli.
Salmon Spinach Pasta|Pasta con salmón y espinacas|salmon,pasta,spinach,lemon|Stove|30|Boil pasta; sear salmon and flake it after cooking through.|Hierve pasta; dora salmón y desmenúzalo cuando esté cocido.|Wilt spinach in the pasta pan, add salmon and finish with lemon.|Marchita espinacas en la olla de pasta, agrega salmón y termina con limón.
Salmon Cucumber Rice Bowl|Tazón de salmón con pepino y arroz|salmon,rice,cucumber,avocado|Stove|25|Cook rice and pan-sear salmon until fully cooked; let it rest.|Cuece arroz y dora salmón hasta cocinarlo; deja reposar.|Top rice with flaked salmon, fresh cucumber and sliced avocado.|Cubre el arroz con salmón desmenuzado, pepino y aguacate.
White Fish with Tomato Olives|Pescado en salsa de tomate y aceitunas|white fish,tomatoes,olives,onion|Stove|30|Simmer diced tomatoes, sliced onion and olives into a thick sauce.|Cuece jitomate picado, cebolla rebanada y aceitunas hasta espesar.|Nestle fish in the sauce, cover and cook until it is opaque and done.|Coloca pescado en la salsa, tapa y cuece hasta que esté opaco y hecho.
Fish Tacos with Cabbage|Tacos de pescado con repollo|white fish,tortillas,cabbage,lime|Stove|25|Season and pan-cook fish fillets, then flake into pieces.|Sazona y cocina filetes de pescado en sartén; desmenúzalos.|Fill warm tortillas with fish, shredded cabbage and lime juice.|Rellena tortillas tibias con pescado, repollo rallado y limón.
Baked Fish and Potatoes|Pescado al horno con papas|white fish,potatoes,lemon,onion|Oven|45|Roast sliced potatoes and onions until nearly soft.|Hornea papas y cebolla rebanadas hasta casi ablandar.|Lay fish on top and continue baking until cooked; finish with lemon.|Coloca el pescado encima y hornea hasta cocinarlo; termina con limón.
Fish Chowder|Sopa cremosa de pescado y papa|white fish,potatoes,corn,milk|Stove|40|Simmer potato cubes and corn in water until the potatoes soften.|Cuece papa en cubos y elote en agua hasta ablandar las papas.|Add fish and milk; simmer gently until the fish is cooked and flakes.|Agrega pescado y leche; cuece suave hasta que el pescado se desmenuce.
Tuna Pasta Salad|Ensalada de pasta con atún|tuna,pasta,peas,cucumber|Stove|25|Cook pasta and peas, then cool them promptly under clean cold water.|Cuece pasta y chícharos y enfríalos pronto con agua limpia fría.|Mix drained canned tuna and chopped cucumber into the pasta.|Mezcla atún de lata escurrido y pepino picado con la pasta.
Tuna and White Bean Salad|Ensalada de atún y alubias|tuna,white beans,tomatoes,red onion|No Cook|15|Rinse and drain cooked white beans; chop tomatoes and red onion.|Enjuaga y escurre alubias cocidas; pica jitomate y cebolla morada.|Toss with drained canned tuna and a little lemon or vinegar.|Mezcla con atún enlatado escurrido y un poco de limón o vinagre.
Tuna Stuffed Avocados|Aguacates rellenos de atún|tuna,avocado,tomatoes,corn|No Cook|15|Drain canned tuna and combine it with finely chopped tomatoes and corn.|Escurre atún enlatado y mezcla con jitomate picado y elote.|Spoon filling into halved avocados immediately before serving.|Rellena mitades de aguacate justo antes de servir.
Shrimp Scampi Pasta|Pasta de camarones al ajo y limón|shrimp,pasta,garlic,lemon|Stove|25|Boil pasta; sauté peeled shrimp and garlic until shrimp are opaque.|Hierve pasta; saltea camarones pelados y ajo hasta que estén opacos.|Toss shrimp with pasta, cooking water and lemon juice.|Mezcla camarones con pasta, un poco de su agua y jugo de limón.
Shrimp and Grits|Camarones con sémola cremosa|shrimp,grits,milk,bell pepper|Stove|30|Cook grits gently with milk and water until creamy.|Cuece sémola de maíz lentamente con leche y agua hasta hacerla cremosa.|Sauté shrimp with diced pepper until cooked; spoon over grits.|Saltea camarones con pimiento picado hasta cocer; sirve sobre la sémola.
Shrimp and Mango Tacos|Tacos de camarón con mango|shrimp,mango,tortillas,cabbage|Stove|25|Sear peeled shrimp in a hot pan until opaque and cooked.|Dora camarones pelados en sartén caliente hasta que estén opacos y cocidos.|Pile shrimp, diced mango and shredded cabbage onto warm tortillas.|Sirve camarón, mango picado y repollo rallado en tortillas tibias.
Shrimp Vegetable Fried Rice|Arroz frito con camarones y verduras|shrimp,rice,carrot,peas|Stove|25|Cook rice ahead of time; sauté shrimp separately until done.|Prepara arroz con anticipación; saltea camarones aparte hasta cocer.|Stir-fry cooked rice with carrot and peas, then return shrimp to heat.|Saltea arroz cocido con zanahoria y chícharos; regresa camarones para calentar.
Shrimp Coconut Curry|Curry de camarón y coco|shrimp,coconut milk,bell pepper,rice|Stove|30|Cook rice; simmer bell pepper in coconut milk with curry spices.|Cuece arroz; cocina pimiento en leche de coco con especias de curry.|Add shrimp at the end and simmer just until opaque; serve with rice.|Agrega camarones al final y cuece hasta opacar; sirve con arroz.
Shrimp Avocado Salad|Ensalada de camarón y aguacate|shrimp,avocado,cucumber,lettuce|Stove|20|Poach peeled shrimp in gently simmering water until cooked; cool promptly.|Cuece camarones pelados en agua a hervor suave y enfría pronto.|Serve cooled shrimp with washed lettuce, diced cucumber and avocado.|Sirve camarón frío con lechuga lavada, pepino y aguacate picados.
Shrimp and Corn Soup|Sopa de camarón y elote|shrimp,corn,potatoes,carrot|Stove|35|Simmer diced potatoes, carrot and corn in water until tender.|Cuece papas, zanahoria y elote en agua hasta ablandar.|Add peeled shrimp in the last few minutes; cook until opaque.|Agrega camarones pelados en los últimos minutos y cuece hasta opacar.
Shrimp and Zucchini Skillet|Camarones con calabacita al sartén|shrimp,zucchini,tomatoes,garlic|Stove|25|Sauté zucchini pieces until browned, then add chopped tomato.|Saltea trozos de calabacita hasta dorar y agrega jitomate picado.|Add shrimp and garlic, stirring until shrimp are cooked and sauce thickens.|Agrega camarones y ajo; mueve hasta cocer camarones y espesar salsa.
Spinach Feta Omelet|Omelette de espinaca y feta|eggs,spinach,feta,tomatoes|Stove|15|Whisk eggs and pour into a lightly oiled nonstick skillet.|Bate huevos y vierte en sartén antiadherente con poco aceite.|Add wilted spinach and feta, fold and cook until eggs are set.|Agrega espinacas marchitas y feta, dobla y cocina hasta cuajar.
Mushroom and Cheese Omelet|Omelette de champiñones y queso|eggs,mushrooms,cheese,onion|Stove|15|Brown sliced mushrooms and onion in a skillet and set aside.|Dora champiñones y cebolla rebanados en un sartén y aparta.|Pour in beaten eggs, add mushrooms and cheese, fold and cook until set.|Vierte huevos batidos, agrega champiñones y queso, dobla y cuaja.
Spanish Potato Tortilla|Tortilla española de papa|eggs,potatoes,onion|Stove|35|Cook thin potato and onion slices slowly in an oiled skillet until soft.|Cocina lentamente rebanadas delgadas de papa y cebolla con aceite.|Mix with beaten eggs and set both sides of the thick tortilla over gentle heat.|Mezcla con huevo batido y cuaja ambos lados a fuego suave.
Egg and Black Bean Breakfast Tacos|Tacos de huevo y frijoles negros|eggs,black beans,tortillas,tomatoes|Stove|20|Warm cooked black beans and scramble eggs in a separate skillet.|Calienta frijoles negros cocidos y revuelve huevos en otro sartén.|Fill warm tortillas with egg, beans and chopped tomatoes.|Rellena tortillas calientes con huevo, frijoles y jitomate picado.
Egg and Avocado Breakfast Toast|Pan tostado con huevo y aguacate|eggs,avocado,bread,tomatoes|Stove|15|Toast bread while cooking eggs in a lightly oiled skillet until set.|Tuesta pan mientras cuajas los huevos en un sartén con poco aceite.|Mash avocado onto toast and top with eggs and chopped tomato.|Machaca aguacate sobre el pan y cubre con huevo y jitomate picado.
Egg Salad Sandwich|Sándwich de ensalada de huevo|eggs,bread,celery,yogurt|Stove|25|Hard-boil eggs, cool, peel and chop with washed celery.|Hierve huevos hasta cocer bien, enfría, pela y pica con apio lavado.|Bind with yogurt and spoon between slices of toasted bread.|Mezcla con yogur y pon entre rebanadas de pan tostado.
Tomato Basil Frittata|Frittata de jitomate y albahaca|eggs,tomatoes,mozzarella,basil|Oven|25|Whisk eggs and pour over softened tomatoes in an oven-safe pan.|Bate huevos y vierte sobre jitomates ablandados en sartén apto para horno.|Scatter mozzarella and basil; bake until center is set.|Reparte mozzarella y albahaca; hornea hasta cuajar el centro.
Broccoli Cheddar Frittata|Frittata de brócoli y queso|eggs,broccoli,cheese,milk|Oven|30|Steam small broccoli florets and place in a greased baking dish.|Cuece pequeños ramilletes de brócoli al vapor y pon en molde engrasado.|Pour in whisked eggs with milk and cheese; bake until firm.|Vierte huevos batidos con leche y queso; hornea hasta cuajar.
Egg Fried Rice with Peas|Arroz frito con huevo y chícharos|eggs,rice,peas,carrot|Stove|20|Scramble eggs in a hot skillet and move them to a clean plate.|Revuelve huevos en sartén caliente y pásalos a un plato limpio.|Stir-fry cooked rice, peas and carrot; return eggs and heat through.|Saltea arroz cocido, chícharos y zanahoria; agrega huevo y calienta.
Cheese and Spinach Crepes|Crepas de queso y espinaca|eggs,flour,milk,spinach,cheese|Stove|35|Whisk eggs, flour and milk into a thin batter; cook thin crepes in a skillet.|Bate huevos, harina y leche hasta hacer masa ligera; cocina crepas finas.|Wilt spinach, fill crepes with spinach and cheese, and heat until melted.|Marchita espinaca, rellena crepas con ella y queso, y calienta hasta derretir.
Breakfast Egg Muffins|Muffins de huevo con pimiento|eggs,bell pepper,cheese,spinach|Oven|25|Divide chopped pepper and spinach among greased muffin cups.|Reparte pimiento y espinaca picados en moldes para muffins engrasados.|Pour beaten eggs over vegetables, add cheese and bake until centers set.|Cubre verduras con huevos batidos, agrega queso y hornea hasta cuajar.
Eggs Florentine Toast|Pan tostado con huevo y espinaca|eggs,bread,spinach,tomatoes|Stove|20|Toast bread, wilt spinach and cook eggs to your desired fully set texture.|Tuesta pan, marchita espinacas y cocina huevos hasta cuajar.|Layer toast with spinach, egg and fresh chopped tomato.|Sirve sobre pan la espinaca, el huevo y jitomate fresco picado.
Potato and Egg Breakfast Burrito|Burrito de papa y huevo|eggs,potatoes,tortillas,cheese|Stove|30|Brown diced potatoes in a covered pan until soft; scramble the eggs.|Dora papas en cubos en sartén tapado hasta suavizar; revuelve huevos.|Wrap potatoes and eggs in warm tortillas with a little cheese.|Envuelve papas y huevos en tortillas tibias con un poco de queso.
Zucchini and Ricotta Frittata|Frittata de calabacita y ricotta|eggs,zucchini,ricotta,onion|Oven|30|Sauté zucchini and onion until their moisture cooks off.|Saltea calabacita y cebolla hasta evaporar el líquido.|Pour beaten eggs into an oven-safe dish, dollop ricotta and bake until set.|Vierte huevos batidos en recipiente para horno, agrega ricotta y cuaja.
Mushroom Quiche|Quiche de champiñones|eggs,mushrooms,pastry,milk|Oven|50|Blind-bake a pastry shell and sauté mushrooms until their water evaporates.|Prehornea una base de masa y saltea champiñones hasta evaporar el agua.|Pour beaten eggs and milk over mushrooms in the shell; bake until set.|Vierte huevos batidos con leche sobre champiñones en la base; hornea hasta cuajar.
Baked Eggs in Avocado|Huevos horneados en aguacate|eggs,avocado,tomatoes|Oven|20|Scoop a little flesh from avocado halves so each can hold an egg.|Retira un poco de pulpa de las mitades de aguacate para que quepa un huevo.|Crack an egg into each, bake until set, then top with chopped tomato.|Pon un huevo en cada mitad, hornea hasta cuajar y añade jitomate.
Huevos Rancheros|Huevos rancheros|eggs,tortillas,beans,tomatoes|Stove|25|Warm tortillas and cooked beans; simmer chopped tomatoes into a sauce.|Calienta tortillas y frijoles cocidos; cuece jitomate picado para hacer salsa.|Cook eggs until set, then place on tortillas over beans and tomato sauce.|Cocina huevos hasta cuajar y sirve en tortillas con frijoles y salsa.
Spinach Egg Drop Soup|Sopa de huevo con espinacas|eggs,spinach,carrot,green onion|Stove|20|Simmer shredded carrot in broth until tender, then add spinach.|Cuece zanahoria rallada en caldo hasta suavizar; agrega espinacas.|Slowly pour beaten eggs into gently bubbling broth while stirring; cook fully.|Vierte huevos batidos despacio en caldo a hervor suave moviendo; cuece bien.
Lentil and Spinach Dal|Dal de lentejas con espinaca|lentils,spinach,tomatoes,onion|Stove|45|Simmer rinsed lentils with tomato, onion and water until soft.|Cuece lentejas enjuagadas con jitomate, cebolla y agua hasta suavizar.|Stir in spinach and curry spices; cook until wilted and creamy.|Agrega espinacas y especias de curry; cuece hasta marchitar y espesar.
Lentil and Potato Stew|Guiso de lentejas y papa|lentils,potatoes,carrot,onion|Stove|45|Simmer rinsed lentils and diced potatoes in water until almost soft.|Cuece lentejas enjuagadas y papas picadas en agua hasta casi ablandar.|Add carrot and onion; continue simmering until everything is tender.|Agrega zanahoria y cebolla; sigue cociendo hasta suavizar todo.
Lentil Stuffed Peppers|Pimientos rellenos de lentejas|lentils,bell pepper,rice,tomatoes|Oven|45|Cook lentils and rice separately; mix with chopped tomatoes.|Cuece lentejas y arroz por separado; mezcla con jitomates picados.|Pack mixture into pepper halves and bake covered until peppers soften.|Rellena mitades de pimiento y hornea tapado hasta que se ablanden.
Lentil Shepherd's Pie|Pastel de lentejas con puré de papa|lentils,potatoes,peas,carrot|Oven|50|Cook lentils until tender; boil potatoes and mash them.|Cuece lentejas hasta ablandar; hierve papas y hazlas puré.|Combine lentils with peas and carrots; top with mash and bake until golden.|Mezcla lentejas con chícharos y zanahoria; cubre con puré y hornea.
Lentil Mushroom Tacos|Tacos de lentejas y champiñones|lentils,mushrooms,tortillas,onion|Stove|35|Cook lentils until tender; sauté minced mushrooms with onion until brown.|Cuece lentejas hasta suavizar; saltea champiñones picados con cebolla.|Mash some lentils into the mushrooms, season with cumin and serve in tortillas.|Machaca algunas lentejas con hongos, sazona con comino y sirve en tortillas.
Lentil and Pumpkin Soup|Sopa de lentejas y calabaza|lentils,pumpkin,carrot,onion|Stove|45|Simmer rinsed lentils with diced pumpkin and carrot until soft.|Cuece lentejas enjuagadas con calabaza y zanahoria picadas hasta ablandar.|Blend a portion of the soup and return it to the pot for a thicker texture.|Licua una parte de la sopa y regrésala a la olla para espesarla.
Chickpea Spinach Curry|Curry de garbanzos y espinaca|chickpeas,spinach,tomatoes,coconut milk|Stove|30|Simmer cooked chickpeas with crushed tomato and coconut milk.|Cuece garbanzos cocidos con jitomate triturado y leche de coco.|Add spinach and curry spices; heat until spinach wilts.|Agrega espinacas y especias de curry; calienta hasta marchitar.
Chickpea Tomato Stew|Guiso de garbanzos y jitomate|chickpeas,tomatoes,bell pepper,onion|Stove|30|Soften onion and pepper, then add chopped tomatoes and simmer.|Ablanda cebolla y pimiento; agrega jitomate picado y cuece.|Stir in drained cooked chickpeas and reduce until the sauce clings.|Añade garbanzos cocidos escurridos y reduce hasta que la salsa se adhiera.
Chickpea Cucumber Pita|Pita de garbanzos y pepino|chickpeas,pita,cucumber,yogurt|No Cook|15|Mash cooked chickpeas with lemon juice and a pinch of salt.|Machaca garbanzos cocidos con jugo de limón y una pizca de sal.|Stuff warm pita with mash, diced cucumber and yogurt.|Rellena pita tibia con puré, pepino picado y yogur.
Chickpea and Sweet Potato Bowls|Tazones de garbanzos y camote|chickpeas,sweet potatoes,spinach,rice|Oven|40|Roast diced sweet potato until tender and brown at the edges.|Hornea camote en cubos hasta suavizar y dorar los bordes.|Warm cooked chickpeas and spinach; serve everything over rice.|Calienta garbanzos cocidos y espinacas; sirve todo sobre arroz.
Chickpea Pasta with Lemon|Pasta con garbanzos y limón|chickpeas,pasta,lemon,spinach|Stove|25|Boil pasta; warm drained cooked chickpeas in a skillet.|Hierve pasta; calienta garbanzos cocidos escurridos en un sartén.|Toss pasta with chickpeas, wilted spinach, lemon and cooking water.|Mezcla pasta con garbanzos, espinacas marchitas, limón y agua de cocción.
Chickpea and Cauliflower Curry|Curry de garbanzos y coliflor|chickpeas,cauliflower,tomatoes,coconut milk|Stove|35|Simmer cauliflower in crushed tomato and coconut milk until tender.|Cuece coliflor en jitomate triturado y leche de coco hasta ablandar.|Add cooked chickpeas and curry spices; simmer until heated through.|Agrega garbanzos cocidos y curry; cuece hasta calentar bien.
Black Bean and Corn Quesadillas|Quesadillas de frijoles negros y elote|black beans,corn,tortillas,cheese|Stove|20|Warm and drain cooked black beans and corn; spread onto tortillas.|Calienta y escurre frijoles negros cocidos y elote; pon en tortillas.|Add cheese, fold and toast both sides until melted and crisp.|Agrega queso, dobla y dora ambos lados hasta derretir.
Black Bean Sweet Potato Tacos|Tacos de frijoles negros y camote|black beans,sweet potatoes,tortillas,cabbage|Oven|35|Roast small sweet potato cubes until tender; warm cooked black beans.|Hornea cubitos de camote hasta suavizar; calienta frijoles negros cocidos.|Fill warm tortillas with camote, beans and shredded cabbage.|Rellena tortillas tibias con camote, frijoles y repollo rallado.
Black Bean Rice Burgers|Hamburguesas de frijoles y arroz|black beans,rice,breadcrumbs,onion|Stove|30|Mash cooked black beans with cooked rice, breadcrumbs and minced onion.|Machaca frijoles negros cocidos con arroz cocido, pan molido y cebolla.|Form firm patties, refrigerate briefly and brown both sides in a skillet.|Forma tortitas firmes, refrigera un poco y dora ambos lados en sartén.
Black Bean Tortilla Soup|Sopa de frijoles negros y tortilla|black beans,tomatoes,tortilla chips,corn|Stove|30|Simmer cooked black beans with tomatoes, corn and water.|Cuece frijoles negros cocidos con jitomate, elote y agua.|Blend a ladle of beans to thicken and add tortilla chips at serving.|Licua un cucharón de frijoles para espesar y agrega totopos al servir.
White Bean and Kale Soup|Sopa de alubias y col rizada|white beans,kale,carrot,onion|Stove|35|Simmer chopped carrot and onion in broth until tender.|Cuece zanahoria y cebolla picadas en caldo hasta suavizar.|Add cooked white beans and shredded kale; simmer until kale softens.|Agrega alubias cocidas y col rizada picada; cuece hasta suavizar.
White Bean Tomato Toast|Tostadas de alubias con jitomate|white beans,bread,tomatoes,garlic|Stove|20|Cook chopped tomatoes with garlic until they become saucy.|Cuece jitomate picado con ajo hasta formar salsa.|Fold in drained cooked beans and spoon over sturdy toasted bread.|Agrega alubias cocidas escurridas y sirve sobre pan bien tostado.
Pinto Bean and Cheese Molletes|Molletes de frijoles pintos y queso|pinto beans,bread,cheese,tomatoes|Oven|20|Mash cooked pinto beans and spread on halved toasted rolls.|Machaca frijoles pintos cocidos y úntalos en mitades de pan tostado.|Sprinkle cheese, broil briefly to melt, then top with chopped tomatoes.|Agrega queso, gratina brevemente y cubre con jitomate picado.
Pinto Bean Vegetable Soup|Sopa de frijoles pintos y verduras|pinto beans,carrot,zucchini,tomatoes|Stove|30|Simmer carrot and zucchini with chopped tomatoes until tender.|Cuece zanahoria y calabacita con jitomate picado hasta suavizar.|Add cooked pinto beans and heat through; mash a few for body.|Agrega frijoles pintos cocidos y calienta; machaca algunos para espesar.
Crispy Tofu Lettuce Wraps|Tacos de lechuga con tofu crujiente|tofu,lettuce,carrot,soy sauce|Stove|25|Press and crumble firm tofu; brown it in a hot oiled skillet.|Prensa y desmenuza tofu firme; dóralo en sartén caliente con aceite.|Stir in grated carrot and soy sauce, then spoon into washed lettuce leaves.|Agrega zanahoria rallada y salsa de soya; sirve en hojas lavadas de lechuga.
Tofu Vegetable Curry|Curry de tofu y verduras|tofu,carrot,bell pepper,coconut milk|Stove|35|Brown tofu cubes; simmer carrots and peppers in coconut milk.|Dora cubos de tofu; cuece zanahoria y pimientos en leche de coco.|Return tofu with curry spices and simmer until vegetables are tender.|Regresa tofu con curry y cocina hasta ablandar verduras.
Tofu Scramble with Spinach|Tofu revuelto con espinacas|tofu,spinach,tomatoes,onion|Stove|20|Crumble firm tofu and sauté it with chopped onion.|Desmenuza tofu firme y saltéalo con cebolla picada.|Fold in tomatoes and spinach; cook off excess moisture.|Agrega jitomates y espinacas; cocina hasta evaporar exceso de líquido.
Tofu Peanut Noodles|Fideos de tofu con salsa de cacahuate|tofu,noodles,peanut butter,cucumber|Stove|30|Boil noodles and brown diced tofu in a separate pan.|Hierve fideos y dora tofu en cubos en otro sartén.|Thin peanut butter with warm water, toss with noodles and tofu; add cucumber.|Diluye crema de cacahuate en agua tibia, mezcla con fideos y tofu; agrega pepino.
`;
const finalRows = `
Mushroom Risotto|Risotto de champiñones|rice,mushrooms,onion,parmesan|Stove|45|Toast rice with onion, then add warm broth a ladle at a time, stirring.|Tuesta arroz con cebolla; agrega caldo caliente cucharón por cucharón, moviendo.|Brown mushrooms separately and fold in with parmesan when rice is creamy.|Dora hongos aparte y agrega con parmesano cuando el arroz esté cremoso.
Roasted Vegetable Couscous|Cuscús con verduras asadas|couscous,zucchini,bell pepper,chickpeas|Oven|35|Roast zucchini and peppers until browned; soak couscous in hot water.|Hornea calabacita y pimientos hasta dorar; hidrata cuscús en agua caliente.|Fluff couscous and toss with roasted vegetables and cooked chickpeas.|Esponja el cuscús y mezcla con verduras asadas y garbanzos cocidos.
Eggplant Parmesan|Berenjena a la parmesana|eggplant,tomatoes,mozzarella,parmesan|Oven|50|Roast sliced eggplant until soft; simmer tomatoes into a sauce.|Hornea berenjena en rebanadas hasta suavizar; cuece jitomates para hacer salsa.|Layer eggplant with sauce and cheeses, then bake until bubbling.|Alterna berenjena con salsa y quesos y hornea hasta burbujear.
Roasted Sweet Potato and Corn Salad|Ensalada de camote asado y elote|sweet potatoes,corn,lettuce,lime|Oven|35|Roast small sweet potato cubes until soft and browned; warm the corn.|Hornea cubitos de camote hasta suavizar y dorar; calienta el elote.|Cool briefly and toss with washed lettuce, corn and lime juice.|Enfría un poco y mezcla con lechuga lavada, elote y jugo de limón.
Vegetable Minestrone|Minestrone de verduras|pasta,white beans,zucchini,carrot,tomatoes|Stove|40|Simmer carrot, zucchini and tomatoes in water until nearly tender.|Cuece zanahoria, calabacita y jitomate en agua hasta casi ablandar.|Add small pasta and cooked white beans; cook until pasta is tender.|Agrega pasta pequeña y alubias cocidas; cuece hasta ablandar la pasta.
Carrot Ginger Soup|Crema de zanahoria y jengibre|carrot,ginger,milk,onion|Stove|35|Simmer chopped carrot, onion and ginger in water until carrots are tender.|Cuece zanahoria, cebolla y jengibre picados en agua hasta suavizar.|Blend with a little milk; warm gently and season before serving.|Licua con un poco de leche; calienta suavemente y sazona antes de servir.
Cauliflower Potato Soup|Crema de coliflor y papa|cauliflower,potatoes,onion,milk|Stove|35|Simmer cauliflower, diced potato and onion until fork-tender.|Cuece coliflor, papa picada y cebolla hasta suavizar.|Blend with a little milk and reheat gently without boiling hard.|Licua con un poco de leche y calienta suave sin hervir fuerte.
Butternut Squash Soup|Crema de calabaza de invierno|butternut squash,carrot,onion,milk|Stove|40|Simmer peeled squash cubes with carrot and onion until tender.|Cuece cubos de calabaza pelada con zanahoria y cebolla hasta ablandar.|Blend smooth with milk, then warm gently and season.|Licua con leche hasta alisar, calienta suavemente y sazona.
Tomato Basil Pasta|Pasta con jitomate y albahaca|pasta,tomatoes,basil,parmesan|Stove|25|Boil pasta and reserve a cup of its cooking water.|Hierve pasta y guarda una taza del agua de cocción.|Simmer chopped tomatoes, toss in pasta and basil, and finish with parmesan.|Cuece jitomate picado, mezcla con pasta y albahaca y agrega parmesano.
Spinach Ricotta Stuffed Shells|Conchitas rellenas de espinaca y ricotta|pasta shells,spinach,ricotta,tomatoes|Oven|45|Boil large pasta shells; mix wilted spinach with ricotta.|Hierve conchas grandes de pasta; mezcla espinacas marchitas con ricotta.|Stuff shells, arrange in tomato sauce and bake covered until hot.|Rellena conchas, acomoda en salsa de jitomate y hornea tapadas.
Pasta Primavera|Pasta primavera con verduras|pasta,zucchini,peas,carrot,parmesan|Stove|30|Boil pasta; sauté sliced zucchini and carrot until just tender.|Hierve pasta; saltea calabacita y zanahoria rebanadas hasta suavizar.|Toss pasta with vegetables, peas, cooking water and parmesan.|Mezcla pasta con verduras, chícharos, su agua y parmesano.
Roasted Cauliflower Tacos|Tacos de coliflor asada|cauliflower,tortillas,cabbage,yogurt|Oven|35|Season cauliflower florets and roast until browned and tender.|Sazona coliflor en ramilletes y hornea hasta dorar y suavizar.|Fill warm tortillas with cauliflower, cabbage and a spoon of yogurt.|Rellena tortillas tibias con coliflor, repollo y una cucharada de yogur.
Mushroom Spinach Quesadillas|Quesadillas de hongos y espinacas|mushrooms,spinach,tortillas,cheese|Stove|20|Cook mushrooms until browned; wilt the spinach in the same pan.|Cocina champiñones hasta dorar; marchita espinaca en el mismo sartén.|Fill tortillas with vegetables and cheese and toast until melted.|Rellena tortillas con verduras y queso y dora hasta derretir.
Vegetable Fried Rice|Arroz frito de verduras|rice,peas,carrot,green onion|Stove|20|Stir-fry diced carrots and peas until hot and tender.|Saltea zanahoria picada y chícharos hasta calentar y ablandar.|Add cold cooked rice and green onion; fry until steaming and separated.|Agrega arroz cocido frío y cebollín; fríe hasta calentar y separar.
Roasted Broccoli and Potato Tray|Charola de brócoli y papa asados|broccoli,potatoes,onion,parmesan|Oven|40|Roast small potato cubes and onion for twenty minutes.|Hornea cubitos de papa y cebolla durante veinte minutos.|Add broccoli, roast until tender, and sprinkle parmesan at the end.|Agrega brócoli, hornea hasta ablandar y espolvorea parmesano.
Zucchini Corn Fritters|Tortitas de calabacita y elote|zucchini,corn,eggs,flour|Stove|25|Grate zucchini and squeeze out water; mix with corn, egg and flour.|Ralla calabacita y exprime el agua; mezcla con elote, huevo y harina.|Drop spoonfuls into an oiled pan and cook both sides until set and browned.|Pon cucharadas en sartén con aceite y cocina ambos lados hasta cuajar.
Vegetable Pot Pie|Pay de verduras|peas,carrot,potatoes,pastry|Oven|50|Cook diced carrots and potatoes until soft; thicken broth with a little flour.|Cuece zanahoria y papa picadas hasta suavizar; espesa el caldo con harina.|Add peas, cover with pastry and bake until the crust is golden.|Agrega chícharos, cubre con masa y hornea hasta dorar la cubierta.
Cheese and Tomato Flatbread|Pan plano con jitomate y queso|flatbread,tomatoes,mozzarella,basil|Oven|20|Place sliced tomatoes and mozzarella over a flatbread.|Coloca jitomate rebanado y mozzarella sobre pan plano.|Bake until crust is crisp and cheese bubbles; add fresh basil afterward.|Hornea hasta dorar pan y derretir queso; añade albahaca fresca al salir.
Spinach and Cheese Stuffed Potatoes|Papas rellenas de espinacas y queso|potatoes,spinach,cheese,yogurt|Oven|55|Bake pierced whole potatoes until the center is soft.|Hornea papas enteras perforadas hasta suavizar el centro.|Scoop out some flesh, mash with cooked spinach and yogurt, refill and melt cheese.|Saca un poco de pulpa, mezcla con espinaca y yogur, rellena y funde queso.
Sweet Potato and Kale Hash|Salteado de camote y col rizada|sweet potatoes,kale,onion,eggs|Stove|35|Brown diced sweet potato and onion in a covered pan until tender.|Dora camote y cebolla en cubos en sartén tapado hasta ablandar.|Add chopped kale to wilt, then crack in eggs and cook until set.|Agrega col rizada picada hasta marchitar; añade huevos y cocina hasta cuajar.
Stuffed Eggplant Boats|Berenjenas rellenas de verduras|eggplant,tomatoes,chickpeas,cheese|Oven|45|Roast halved eggplants until soft; scoop and chop the flesh.|Hornea mitades de berenjena hasta ablandar; saca y pica la pulpa.|Mix pulp with tomatoes and cooked chickpeas, refill and melt cheese on top.|Mezcla pulpa con jitomate y garbanzos cocidos, rellena y derrite queso.
Corn and Zucchini Chowder|Sopa cremosa de elote y calabacita|corn,zucchini,potatoes,milk|Stove|35|Simmer small potato cubes with corn until potatoes soften.|Cuece cubitos de papa con elote hasta ablandar la papa.|Add diced zucchini and milk; heat gently until zucchini is tender.|Agrega calabacita en cubos y leche; calienta suave hasta ablandar.
Pea and Parmesan Risotto|Risotto de chícharos y parmesano|rice,peas,onion,parmesan|Stove|40|Toast rice with onion and add warm broth gradually, stirring often.|Tuesta arroz con cebolla y agrega caldo caliente poco a poco, moviendo.|Stir in peas near the end and parmesan when rice is creamy.|Agrega chícharos casi al final y parmesano cuando el arroz esté cremoso.
Mushroom Barley Stew|Guiso de cebada y champiñones|barley,mushrooms,carrot,onion|Stove|55|Simmer barley with water until almost tender.|Cuece cebada en agua hasta que esté casi suave.|Brown mushrooms with onion and carrot; fold into barley and simmer until thick.|Dora hongos con cebolla y zanahoria; mezcla con cebada y espesa.
Baked Ratatouille|Verduras al horno estilo ratatouille|eggplant,zucchini,tomatoes,bell pepper|Oven|45|Slice eggplant and zucchini evenly and arrange over chopped tomatoes.|Rebana berenjena y calabacita parejo y acomoda sobre jitomate picado.|Add sliced pepper, drizzle with oil and bake covered until tender.|Agrega pimiento rebanado, un poco de aceite y hornea tapado hasta suavizar.
Greek Cucumber Chickpea Salad|Ensalada griega de pepino y garbanzos|chickpeas,cucumber,tomatoes,feta|No Cook|15|Rinse cooked chickpeas; chop cucumber and tomatoes into small pieces.|Enjuaga garbanzos cocidos; pica pepino y jitomate en trocitos.|Toss with crumbled feta and lemon juice; serve chilled.|Mezcla con queso feta desmoronado y jugo de limón; sirve frío.
Caprese Tomato Sandwich|Sándwich caprese de jitomate|bread,tomatoes,mozzarella,basil|No Cook|15|Toast bread and slice tomatoes and mozzarella.|Tuesta pan y rebana jitomates y mozzarella.|Layer tomato, mozzarella and basil; press lightly and serve.|Acomoda jitomate, mozzarella y albahaca; presiona un poco y sirve.
Vegetable Soba Noodles|Fideos soba con verduras|soba noodles,carrot,broccoli,soy sauce|Stove|25|Boil soba noodles according to the package and rinse briefly.|Hierve fideos soba según el paquete y enjuaga brevemente.|Stir-fry carrot and broccoli until tender; toss with noodles and soy sauce.|Saltea zanahoria y brócoli hasta ablandar; mezcla con fideos y soya.
Roasted Beet and Goat Cheese Salad|Ensalada de betabel asado y queso de cabra|beets,goat cheese,lettuce,walnuts|Oven|50|Wrap beets in foil and roast until a fork slides in easily; cool and peel.|Envuelve betabeles en aluminio y hornea hasta suavizar; enfría y pela.|Slice beets over washed lettuce; scatter goat cheese and walnuts.|Rebana betabel sobre lechuga lavada y agrega queso de cabra y nueces.
`;

const translations: Record<string,string> = {
 chicken:'pollo',orzo:'pasta orzo',lemon:'limón',spinach:'espinacas',mushrooms:'champiñones',yogurt:'yogur',pasta:'pasta',pesto:'pesto',tomatoes:'jitomates',noodles:'fideos',carrot:'zanahoria',celery:'apio',broccoli:'brócoli',rice:'arroz','soy sauce':'salsa de soya',tortillas:'tortillas',tostadas:'tostadas',lettuce:'lechuga',parmesan:'queso parmesano',breadcrumbs:'pan molido',mozzarella:'queso mozzarella',pita:'pan pita',cucumber:'pepino','sweet potatoes':'camotes','coconut milk':'leche de coco','salsa verde':'salsa verde',cheese:'queso',corn:'elote',potatoes:'papas',peas:'chícharos',pastry:'masa para pay',cabbage:'repollo',onion:'cebolla',honey:'miel',garlic:'ajo','lasagna sheets':'láminas de lasaña',ricotta:'queso ricotta',avocado:'aguacate',hominy:'maíz pozolero',tomatillos:'tomatillos',radishes:'rábanos','black beans':'frijoles negros cocidos','green beans':'ejotes',pineapple:'piña','bell pepper':'pimiento','ground chicken':'pollo molido',zucchini:'calabacita','ground beef':'carne molida',steak:'bistec','stew beef':'carne de res para guiso',barley:'cebada',bread:'pan',eggplant:'berenjena','kidney beans':'frijoles rojos cocidos','teriyaki sauce':'salsa teriyaki',pork:'cerdo','pork chops':'chuletas de cerdo',apple:'manzana','barbecue sauce':'salsa barbacoa',turkey:'pavo molido','cooked turkey':'pavo cocido','ground pork':'cerdo molido','dumpling wrappers':'obleas para empanaditas',ginger:'jengibre','white beans':'alubias cocidas',salmon:'salmón','canned salmon':'salmón enlatado',eggs:'huevos',dill:'eneldo','white fish':'filete de pescado blanco',olives:'aceitunas',lime:'limón verde',tuna:'atún enlatado','red onion':'cebolla morada',shrimp:'camarones',grits:'sémola de maíz',mango:'mango',milk:'leche',feta:'queso feta',basil:'albahaca',flour:'harina',lentils:'lentejas',pumpkin:'calabaza',chickpeas:'garbanzos cocidos','pinto beans':'frijoles pintos cocidos',beans:'frijoles cocidos',kale:'col rizada',tofu:'tofu','peanut butter':'crema de cacahuate',couscous:'cuscús','butternut squash':'calabaza de invierno','pasta shells':'conchas de pasta',flatbread:'pan plano','green onion':'cebollín',beets:'betabeles','goat cheese':'queso de cabra',walnuts:'nueces','soba noodles':'fideos soba','tortilla chips':'totopos',orange:'naranja','cranberry sauce':'salsa de arándanos',cauliflower:'coliflor',grains:'granos','caesar dressing':'aderezo César'
};
const methodSteps: Record<string,[string,string]> = {
 Stove:['Heat a large skillet or pot over medium heat; have clean utensils ready.','Calienta un sartén u olla a fuego medio; prepara utensilios limpios.'],
 Oven:['Preheat the oven to 400°F (200°C) and prepare a baking dish or tray.','Precalienta el horno a 200 °C y prepara un molde o charola.'],
 'No Cook':['Use a clean board and plates to assemble the ingredients.','Usa una tabla y platos limpios para preparar los ingredientes.']
};
function safeFinish(foods:string[]): [string,string] {
 if (foods.some(f => ['chicken','ground chicken','turkey'].includes(f))) return ['Check poultry reaches 165°F (74°C) in the thickest part; serve while hot.','Verifica que el pollo o pavo llegue a 74 °C en la parte más gruesa; sirve caliente.'];
 if (foods.some(f => ['ground beef','ground pork'].includes(f))) return ['Check ground meat reaches 160°F (71°C) in the center; serve while hot.','Verifica que la carne molida llegue a 71 °C en el centro; sirve caliente.'];
 if (foods.some(f => ['salmon','white fish'].includes(f))) return ['Check fish reaches 145°F (63°C) in the thickest part; serve promptly.','Verifica que el pescado alcance 63 °C en la parte más gruesa; sirve enseguida.'];
 if (foods.includes('shrimp')) return ['Check shrimp are opaque and firm throughout; serve promptly.','Comprueba que los camarones estén opacos y firmes; sirve enseguida.'];
 if (foods.includes('pork') || foods.includes('pork chops')) return ['Check whole-cut pork reaches 145°F (63°C); rest it for 3 minutes before serving.','Verifica que el cerdo en piezas llegue a 63 °C; deja reposar 3 minutos antes de servir.'];
 return ['Taste and adjust seasoning; portion onto clean plates and serve.','Prueba y ajusta la sazón; sirve en platos limpios.'];
}
export const expandedDishes: CuratedDish[] = [rows,moreRows,finalRows].flatMap(group => group.trim().split('\n')).map((line,index) => {
 const parts=line.split('|');
 if (parts.length !== 9) throw new Error(`Bad recipe row ${index}: ${line}`);
 const [en,es,rawFood,method,rawMinutes,cookEn,cookEs,finishEn,finishEs]=parts;
 const food=rawFood.split(',');
 const foodEs=food.map(key => { const value=translations[key]; if (!value) throw new Error(`Missing translation: ${key}`); return value; });
 const pantry=method==='Stove'||method==='Oven'?['oil','salt']:['salt'];
 const pantryEs=pantry.map(key=>key==='oil'?'aceite':'sal');
 const safe=safeFinish(food);
 return {id:`local-${497+index}`,en,es,food,foodEs,method,minutes:Number(rawMinutes),pantry,pantryEs,
  nutritionKeys:food,
  stepsEn:[`Gather ${food.join(', ')} and check what you already have.`,`Rinse produce before cutting it; keep raw meat or fish and their utensils separate from ready-to-eat ingredients.`,methodSteps[method][0],cookEn,finishEn,safe[0]],
  stepsEs:[`Reúne ${foodEs.join(', ')} y revisa cuáles ingredientes ya tienes.`,`Lava las verduras antes de cortarlas; separa la carne o pescado crudos y sus utensilios de los alimentos listos para comer.`,methodSteps[method][1],cookEs,finishEs,safe[1]]
 };
});
